Building ddc-api
Step 1/9 : FROM node:18
18: Pulling from library/node
Digest: sha256:671ee8d49ce2a691fc3082203c5deb9522e0c80042aa0ff40c07f4a25e63668a
Status: Downloaded newer image for node:18
 ---> c9e4d88ad304
Step 2/9 : WORKDIR /usr/src/app
 ---> Running in 516ead1b88b2
Removing intermediate container 516ead1b88b2
 ---> 7866654bc3df
Step 3/9 : COPY  package*.json  ./
 ---> 44a018533e37
Step 4/9 : RUN npm install
 ---> Running in e934adab778f

added 82 packages, and audited 83 packages in 9s

6 packages are looking for funding
  run `npm fund` for details

4 high severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
[91mnpm[0m[91m [0m[91mnotice[0m[91m 
[0m[91mnpm[0m[91m [0m[91mnotice[0m[91m New minor version of npm available! 9.5.1 -> 9.6.5
[0m[91mnpm[0m[91m [0m[91mnotice[0m[91m Changelog: <https://github.com/npm/cli/releases/tag/v9.6.5>
[0m[91mnpm[0m[91m [0m[91mnotice[0m[91m Run `npm install -g npm@9.6.5` to update!
[0m[91mnpm[0m[91m [0m[91mnotice[0m[91m 
[0mRemoving intermediate container e934adab778f
 ---> 4c6a0542af33
Step 5/9 : COPY .   .
 ---> 31c2e6fdbb13
Step 6/9 : ENV PORT=8231
 ---> Running in 545518c042f9
Removing intermediate container 545518c042f9
 ---> ff6ea177bf9b
Step 7/9 : ENV MONGODB_URL=mongodb://root:root@mongoDB.host:27017
 ---> Running in 63f76a8fa7a1
Removing intermediate container 63f76a8fa7a1
 ---> ac9201b7c0d7
Step 8/9 : EXPOSE 8231
 ---> Running in 83d38c2700f8
Removing intermediate container 83d38c2700f8
 ---> 76d26a019879
Step 9/9 : CMD [ "npm", "start" ]
 ---> Running in 532388f48ec4
Removing intermediate container 532388f48ec4
 ---> fb2c6bb05e4b

Successfully built fb2c6bb05e4b
Successfully tagged backend-ddc_ddc-api:latest
Creating backend-ddc-api ... 
[1A[2KCreating backend-ddc-api ... [32mdone[0m[1BAttaching to backend-ddc-api
[36mbackend-ddc-api |[0m 
[36mbackend-ddc-api |[0m > ddc-api@1.0.0 start
[36mbackend-ddc-api |[0m > node server.js
[36mbackend-ddc-api |[0m 
[36mbackend-ddc-api |[0m mongoDbUrl=mongodb://root:root@mongoDB.host:27017
[36mbackend-ddc-api |[0m http://localhost:8231
[36mbackend-ddc-api |[0m Connected correctly to mongodb database
Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
Exception in thread Thread-4:
Traceback (most recent call last):
  File "site-packages/urllib3/connectionpool.py", line 677, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 426, in _make_request
  File "<string>", line 3, in raise_from
  File "site-packages/urllib3/connectionpool.py", line 421, in _make_request
  File "http/client.py", line 1344, in getresponse
  File "http/client.py", line 306, in begin
  File "http/client.py", line 267, in _read_status
  File "socket.py", line 589, in readinto
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/requests/adapters.py", line 449, in send
  File "site-packages/urllib3/connectionpool.py", line 725, in urlopen
  File "site-packages/urllib3/util/retry.py", line 403, in increment
  File "site-packages/urllib3/packages/six.py", line 734, in reraise
  File "site-packages/urllib3/connectionpool.py", line 677, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 426, in _make_request
  File "<string>", line 3, in raise_from
  File "site-packages/urllib3/connectionpool.py", line 421, in _make_request
  File "http/client.py", line 1344, in getresponse
  File "http/client.py", line 306, in begin
  File "http/client.py", line 267, in _read_status
  File "socket.py", line 589, in readinto
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "compose/cli/log_printer.py", line 217, in watch_events
  File "compose/project.py", line 510, in yield_loop
  File "compose/project.py", line 478, in build_container_event
  File "compose/container.py", line 48, in from_id
  File "site-packages/docker/utils/decorators.py", line 19, in wrapped
  File "site-packages/docker/api/container.py", line 758, in inspect_container
  File "site-packages/docker/utils/decorators.py", line 46, in inner
  File "site-packages/docker/api/client.py", line 230, in _get
  File "site-packages/requests/sessions.py", line 546, in get
  File "site-packages/requests/sessions.py", line 533, in request
  File "site-packages/requests/sessions.py", line 646, in send
  File "site-packages/requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

Gracefully stopping... (press Ctrl+C again to force)
